apiVersion: extensions/v1beta1
kind: Ingress
metadata:
name: joomla-ingress
annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
spec:
rules:
- host: DOMAIN
    http:
    paths:
    - path: /
        backend:
        serviceName: ingress-example-joomla
        servicePort: 80
- host: blog.DOMAIN
    http:
    paths:
    - path: /
        backend:
        serviceName: ingress-blog-ghost
        servicePort: 80
tls:
- secretName: joomla-tls-cert
    hosts:
    - DOMAIN
    - blog.DOMAIN
---
apiVersion: v1
kind: Secret
metadata:
  name: testsecret
  namespace: default
data:
  tls.crt: <base64_encoded_cert>
  tls.key: <base64_encoded_key>
type: Opaque
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - example.com
    secretName: testsecret
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: service1
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: ingress-basic
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - demo.azure.com
    secretName: aks-ingress-tls
  rules:
  - host: demo.azure.com
    http:
      paths:
      - backend:
          serviceName: aks-helloworld
          servicePort: 80
        path: /(.*)
      - backend:
          serviceName: ingress-demo
          servicePort: 80
        path: /hello-world-two(/|$)(.*)