apiVersion: v1
kind: Pod
metadata:
  name: jenkins-cicd
  labels:
    app: cicd
spec:
  containers:
  - name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - containerPort: 8080
        hostPort: 8091
    volumeMounts:
      - name: jenkins-data
        mountPath: /var/jenkins_home
    resources:
      limits:
        memory: 1Gi
        cpu: "200m"
      requests:
        memory: 1Gi
        cpu: "200m"
  volumes:
    - name: jenkins-data
      nfs:
        server: 192.168.1.120
        path: /var/jenkins_data